/**
 * Copyright (C) 2017 Cryptox, Blub Corp.
 * All Rights Reserved
 *
 * This file is part of the Cryptox project.
 *
 * Content can not be copied and/or distributed without the express
 * permission of the author.
 */

/// This file is autogenerated by the crygen code generator
/// and should not be altered in critical sections. Doing so may
/// result in untracable diagnostics.

/// Project   :       Cryptox Demo2
/// Name      :       Proposal Acquisition
/// Generated :       2017-09-24 11:58:43
/// Author    :       Blub Corp.
/// Language  :       C Intermediate Language
/// Compiler  :       C99

#pragma crycc optimize level3
#pragma crycc dialect cil08
#pragma crycc standard c99
#pragma crycc entry '1293'

#pragma meta project("1aac4c3d-2c08-4be1-9e9f-451f4f811026")
#pragma meta name("prosacq")
#pragma meta timstamp('1506248672')

#if defined(__CRYCC__)
# include <crylib.h>
#endif
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#pragma unit id '12'
#pragma unit order '4'
#pragma unit object "32bd06f8-47cd-4a33-99d5-f7f855eef494"

#pragma procedure(78263, "Print data as hexadecimal string") {
void print_hex(unsigned char data[], size_t len) {
    printf("[ ");
    for (int i=0; i<len; ++i) {
        printf("%.2x", data[i]);
    }
    printf(" ]\n");
}
#pragma } // 78263

#pragma member(83712) {
static const unsigned char keystream[] = {'a','#','$','*','['};
#pragma } // 83712

#pragma procedure(78178, "XOR input data with modulo keystream") {
int xor(unsigned char data[], size_t len) {
    for (int i=0; i<len; ++i) {
        data[i] ^= keystream[i % sizeof(keystream)];
    }
}
#pragma } // 78178

#pragma procedure(1293, "Application entry") {
int main(int argc, char *argv[]) {
    char str[] = "a testing string";
    printf("Original: %s ", str);
    print_hex(str, sizeof(str));

    xor(str, sizeof(str));
    printf("XOR:");
    print_hex(str, sizeof(str));

    xor(str, sizeof(str));
    printf("Original: %s ", str);
    print_hex(str, sizeof(str));
    return 0;
}
#pragma } // 1293

#pragma assert(0)
